# Dockerfile.base
FROM php:8.4-cli

# System dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libzip-dev \
    libonig-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-install pdo pdo_mysql zip mbstring \
    && rm -rf /var/lib/apt/lists/*

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Node.js (LTS) + pnpm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g pnpm

WORKDIR /app


COPY composer.json composer.lock ./
RUN composer install --no-scripts

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
RUN composer dump-autoload

EXPOSE 8000 5173

CMD pnpm dev:both


